name: eslint the code
on:
  pull_request:
    branches:
#      Uncomment to run on main branch.
#      - main
      - not-real
jobs:
  cypress-run:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup code
        run: yarn

      - name: Lint code
        run: yarn lint
