name: Cypress tests
on:
  pull_request:
    branches:
#     Uncomment to run on main branch.
#       - main
      - not-real
jobs:
  cypress-run:
    name: Cypress run sample test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env: 
          CYPRESS_baseUrl: https://www.cu.edu
        with:
          spec: cypress/integration/sample_spec.js
          
