name: Cypress tests
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    name: Cypress run sample test
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/sample_spec.js
          env: baseUrl=https://www.cu.edu